#
# Module manifest for module 'blachniet'
#
# Generated by: Brian Lachniet
#
# Generated on: 7/16/2013
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'Send-EventEntryEmail'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '86bfd741-6c0a-4c10-a65b-9c4666addbf3'

# Author of this module
Author = 'Esa Ollitervo'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = 'Esa Ollitervo 2020'

# Description of the functionality provided by this module
Description = 'Some PowerShell utilities.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = ''

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}
